### ISSUE TITLE
Return response to host

### ISSUE THREAD

**Issue by ragingwind** [riiid/qtikit#20]
# Progress

- [x] ChoiceInteraction
- [x] ExtendedTextInteraction
- [ ] GapMatchInteraction
- [x] InlineChoiceInteraction
- [x] TextEntryInteraction

**Comment by Il9** [comment]
InteractionResponse
=> {[interaction options identifier]: value}, {**choice1: true**} or {**W: G1**}

QtiViewerResponse
=> {[Interaction response indentifier]: InteractionResponse[]}, {**Response1: ['choice1', ''choice2']**} or {**Response1: ['W G1', 'S G2']**}

**Comment by ragingwind** [comment]
@Il9 We have to change the way of dispatching responses. inputState must keep all of responses

**Comment by ragingwind** [comment]
done
