### ISSUE TITLE
Styling solution

### ISSUE THREAD

**Issue by ragingwind** [riiid/qtikit#21]
Support own stylesheet in Assessment XML

- [ ] Shadow DOM to support scoped CSS
- [ ] React.memo will cause re-rendering in react
- [ ] Using React. createPortal
- [ ] Alternative way to apply scoped CSS

**Comment by ragingwind** [comment]
@Il9 We can talk about styling issues at here :)

**Comment by Il9** [comment]
How about making a theme that can be styled for each component and interaction, and exporting it after applying the default style?

**Comment by Il9** [comment]
It can be overrding

**Comment by disjukr** [comment]
We must also respect the style information (`<stylesheet>`) of the content itself.

**Comment by ragingwind** [comment]
- [ ] React.memo will cause re-rendering in react
- [ ] Using React. createPortal
- [ ] Alternative way to apply scoped CSS
