### ISSUE TITLE
Implement rubricBlock component

### ISSUE THREAD

**Issue by ragingwind** [riiid/qtikit#22]
I've noticed that rubricBlock element. It has own styles because child content represents rubric, note, warning about assessments

- rubricBlock should be ignored while play assessment?
    
    ```gherkin
    A rubricBlock can be used to add instructions about the way the item should be scored by a human scorer. The view attribute is used to indicate that the information should only be made visible to users in certain roles.
    ```

**Comment by Il9** [comment]
i'll Implement with hottextInteraction
